baseURL = "https://memo.touyu.me"
languageCode = "ja"
title = "memo.touyu.me"
theme = "m10c"
paginate = 15

[params]
  author = "touyu"
  description = "This is just a memorandum."
  customCSS = ["/css/custom.css"]
  images = ["static/og.png"]

[params.style]
  # darkestColor = "#463625"
  # darkColor = "#2a3738"
  primaryColor = "#3498db"
  # lightColor = "#96a879"
  # lightestColor = "#ffffff"
  