baseURL = "https://memo.touyu.me"
languageCode = "ja"
title = "memo.touyu.me"
theme = "m10c"
paginate = 15

[params]
  author = "touyu"
  description = "This is just a memorandum."

[params.style]
  # darkestColor = "#00ff00"
  # darkColor = "#ffffff"
  # lightColor = "#242424"
  # lightestColor = "#242424"
  # primaryColor = "#3498db"
  primaryColor = "#3498db"
  